include_recipe "pivotal_workstation::java"
include_recipe "pivotal_workstation::iterm2"
include_recipe "pivotal_workstation::vim"
include_recipe "pivotal_workstation::textmate"
include_recipe "pivotal_workstation::textmate_bundles"
include_recipe "pivotal_workstation::textmate_preferences"
