include_recipe "pivotal_workstation::java"
include_recipe "pivotal_workstation::iterm2"
include_recipe "pivotal_workstation::textmate"
include_recipe "pivotal_workstation::textmate_bundles"
include_recipe "pivotal_workstation::textmate_preferences"
include_recipe "pivotal_workstation::sublime_text_2"
include_recipe "pivotal_workstation::set_screensaver_preferences"